on: [push]

name: Build and deploy Docker app to Azure


env:
  AZURE_WEBAPP_NAME: reactweb
  CONTAINER_REGISTRY: azurewebapps.azurecr.io
  IMAGE_NAME_WITH_TAG: azurewebapps.azurecr.io/reactwebapp:${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure container registry authentication
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ env.IMAGE_NAME_WITH_TAG }}
          docker push ${{ env.IMAGE_NAME_WITH_TAG }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.IMAGE_NAME_WITH_TAG }}