name: webapp cd worflow on azure

on: [push]

jobs:
  push-images-on-azure-registry:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}