name: webapp cd worflow on azure

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: mycontainer.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t reactwebappazurecicd.azurecr.io/reactWebapp:${{ github.sha }}
          docker push reactwebappazurecicd.azurecr.io/reactWebapp:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'reactWebapp'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'reactwebappazurecicd.azurecr.io/reactWebapp:${{ github.sha }}'
